# Generated by Django 4.1.7 on 2023-03-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_value',
            field=models.FloatField(default=0),
        ),
    ]
