# Generated by Django 4.1.7 on 2023-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_full_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Confirmada')], default=1, max_length=1),
        ),
    ]
