# Generated by Django 4.1.7 on 2023-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Confirmada'), ('3', 'Vendido')], default=1, max_length=1),
        ),
    ]
