# Generated by Django 4.1.7 on 2023-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=50)),
                ('nit', models.IntegerField(unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
