# Generated by Django 4.1.7 on 2023-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='shops'),
        ),
    ]
